### ISSUE TITLE
Create Issues Template

### ISSUE THREAD

**Issue by kevinlee12** [kevinlee12/CASCategorization#1]
Create templates for issue tracker and pull requests as mentioned [here](https://github.com/blog/2111-issue-and-pull-request-templates).

**Comment by kevinlee12** [comment]
The template for the issue tracker may have something similar to:

---

## Description

_Details on what the issue/requested feature is. Please be as specific as possible._ 

## System Config
- OS (with version): _List online if the issue/feature is associated with our hosted version_ 
- Browser (with version): _Ex. Chrome v49.0.2623.112, Safari 9.1, Firefox 45.0.1, Edge, etc_

## Steps to Reproduce (if the issue is a bug)
1. 
2. 
3. 

## Expected output

_List your expected behavior here_

## Screenshots/Console Log

_If applicable. Place mock ups here to illustrate new features._

---

comments? @sdulal @nsivapalan 

note: the start and end tags won't appear on the final product.

**Comment by kevinlee12** [comment]
We can probably hold off on the PR side for now, unless you guys think we should have it.

**Comment by nsivapalan** [comment]
good stuff!

**Comment by kevinlee12** [comment]
Completed in ef03a45
