### ISSUE TITLE
Git Pre-push Hook

### ISSUE THREAD

**Issue by kevinlee12** [kevinlee12/CASCategorization#11]
## Description

Create a pre-push hook that will link and check license headers on all applicable files. 
- [x] Add setup script to add pre-push hook
- [x] Lint all Python files 

~~Check all applicable files for license headers~~

**Comment by sdulal** [comment]
We can get a pre-push hook to lint all the python files.

However, checking for license headers is quite extensive and as of right now is not a finalized process (we've yet to determine all types of files that will get headers, and what their header content will be).

**Comment by kevinlee12** [comment]
Open to leaving license to manual review (or Y/n asking if the developer included it in the relevant files).

**Comment by sdulal** [comment]
The hook is incorporated in 594fe1dc1de18f492a0f627c8b09aee44fdfe2fe. Note that it does not have the license header check.
