### ISSUE TITLE
Conda Setup Script

### ISSUE THREAD

**Issue by kevinlee12** [kevinlee12/CASCategorization#3]
Make a bash conda setup script that will install conda and set up the cas environment

**Comment by kevinlee12** [comment]
@sdulal, only because we need a :apple: tester :stuck_out_tongue:

**Comment by kevinlee12** [comment]
@sdulal, forgot to say that we have a Conda setup script for CircleCI in `scripts/`, you might be able to modify that.

**Comment by kevinlee12** [comment]
The script would do the following:
1. Check if conda is installed, if not, install it using either Mac or Linux link:
    - Mac: https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
    - Linux: https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
2. Store the conda path in a .condarc file
3. Activate condarc file
4. Start the environment creation script (TODO: deal with scipy Mac vs Linux version)
5. Pip install `requirements.txt`
6. Run DB setup script
7. `python manage.py test`

**Comment by sdulal** [comment]
Done!
