### ISSUE TITLE
Update Django to 1.9.5

### ISSUE THREAD

**Issue by kevinlee12** [kevinlee12/CASCategorization#9]
- [x] Update Django to 1.9.5
- [x] Fix print statement in scripts/db_setup.sh
- [x] Change `cas_user` to `cas` in db_setup.sh

**Comment by kevinlee12** [comment]
with @sdulal

**Comment by sdulal** [comment]
Fixed in 660c8d1b2f239f02e53d518fa676e0292724ae06.
